# -*- coding: utf-8 -*-
"""y9monkeydetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CQVc_bIWmDuqoU2oM0Caw9Gz6OXW7FY
"""

!nvidia-smi

import os
base = os.getcwd()
print(base)

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/SkalskiP/yolov9.git
# %cd yolov9
!pip install -r requirements.txt -q

!pip install -q roboflow

import roboflow

from IPython.display import Image

!mkdir -p {base}/weights

!wget -P {base}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-c.pt
!wget -P {base}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-e.pt
!wget -P {base}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-c.pt
!wget -P {base}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-e.pt

!ls -la {base}/weights

!mkdir -p {base}/data

SOURCE_IMAGE_PATH = "/content/dc.jpeg"

!python detect.py --weights {base}/weights/yolov9-e.pt --conf 0.1 --source /content/dc.jpeg --device 0

Image(filename=f"{base}/yolov9/runs/detect/exp/dc.jpeg", width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {base}/yolov9

from roboflow import Roboflow
rf = Roboflow(api_key="KnO1HFUawybkKzxGovmP")
project = rf.workspace("nikhil-8yfpr").project("cow_monkey")
version = project.version(3)
dataset = version.download("yolov9")

# Commented out IPython magic to ensure Python compatibility.
# %cd {base}/yolov9

!python train.py \
--batch 2 --epochs 100 --img 640 --device 0 --min-items 0 --close-mosaic 15 \
--data {dataset.location}/data.yaml \
--weights {base}/weights/gelan-c.pt \
--cfg models/detect/gelan-c.yaml \
--hyp hyp.scratch-high.yaml

!ls {base}/yolov9/runs/train/exp/

Image(filename=f"{base}/yolov9/runs/train/exp/results.png", width=1000)

Image(filename=f"{base}/yolov9/runs/train/exp/confusion_matrix.png", width=1000)

Image(filename=f"{base}/yolov9/runs/train/exp/val_batch0_pred.jpg", width=1000)

# Commented out IPython magic to ensure Python compatibility.
# %cd {base}/yolov9

!python val.py \
--img 640 --batch 8 --conf 0.001 --iou 0.7 --device 0 \
--data {dataset.location}/data.yaml \
--weights {base}/yolov9/runs/train/exp/weights/best.pt

!python detect.py \
--img 640 --conf 0.1 --device 0 \
--weights {base}/yolov9/runs/train/exp/weights/best.pt \
--source {dataset.location}/valid/images

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'{base}/yolov9/runs/detect/exp2/*.jpg')[:3]:
      display(Image(filename=image_path, width=400))
      print("\n")

